import type { ComponentType, SVGProps } from "react";
import {
  GamepadIcon,
  HeadphonesIcon,
  HouseIcon,
  LaptopIcon,
  SparklesIcon,
  WatchIcon,
} from "@/components/icons";

type IconType = ComponentType<SVGProps<SVGSVGElement>>;

export type Product = {
  id: string;
  name: string;
  category: string;
  description: string;
  tags: string[];
  href: string;
  image: string;
  alt: string;
  /** Category motif shown faintly over the placeholder image. Absent on real products. */
  icon?: IconType;
  price: number;
  oldPrice: number;
  discount: number;
  rating: number;
  /** Number of customer reviews behind the rating. */
  reviews: number;
  bestseller?: boolean;
  /**
   * Real-catalogue extras. Absent on the mock flash-deals items (which keep the historic
   * $-styled display); present on everything served by lib/catalogue.
   */
  currency?: string;
  /** Manufacturer name from the catalogue (Apple, Dell, …) — the brand in Product schema. */
  brand?: string;
  /** The store the price came from — required by the cart payload once checkout migrates. */
  storeId?: string;
  stock?: number;
  inStock?: boolean;
  slug?: string;
};

/**
 * Mock product catalogue. `flashDeals` (below) is a curated subset used by the
 * homepage carousel; the full list powers the /products page. Swap `image` for
 * real product photos (square, ~800px) — the card layout is unchanged.
 */
export const products: Product[] = [
  {
    id: "aura-watch",
    name: "Aura Smart Watch",
    category: "Wearables",
    description: "Titanium smartwatch with 14-day battery and on-wrist health AI.",
    tags: ["AMOLED", "14-day", "Health AI"],
    href: "/product/aura-watch",
    image: "/mock/products/aura-watch.jpg",
    alt: "Aura Smart Watch on a silver studio backdrop",
    icon: WatchIcon,
    price: 279,
    oldPrice: 399,
    discount: 30,
    rating: 4.8,
    reviews: 2431,
    bestseller: true,
  },
  {
    id: "cyber-headphones",
    name: "Cyber Headphones X",
    category: "Audio",
    description: "Adaptive ANC over-ears with spatial audio and 40-hour battery.",
    tags: ["ANC", "Spatial", "40h"],
    href: "/product/cyber-headphones",
    image: "/mock/products/cyber-headphones.jpg",
    alt: "Cyber Headphones X on a gold studio backdrop",
    icon: HeadphonesIcon,
    price: 199,
    oldPrice: 299,
    discount: 33,
    rating: 4.7,
    reviews: 1204,
  },
  {
    id: "orbit-drone",
    name: "Orbit Drone Mini",
    category: "Aerial",
    description: "Foldable 4K drone with obstacle avoidance and auto-follow.",
    tags: ["4K", "30-min", "Auto-follow"],
    href: "/product/orbit-drone",
    image: "/mock/products/orbit-drone.jpg",
    alt: "Orbit Drone Mini on a green studio backdrop",
    icon: SparklesIcon,
    price: 449,
    oldPrice: 649,
    discount: 31,
    rating: 4.6,
    reviews: 876,
    bestseller: true,
  },
  {
    id: "vortex-vr",
    name: "Vortex VR Lens",
    category: "Mixed Reality",
    description: "Pancake-lens mixed-reality headset with 4K-per-eye clarity.",
    tags: ["4K/eye", "Passthrough", "120Hz"],
    href: "/product/vortex-vr",
    image: "/mock/products/vortex-vr.jpg",
    alt: "Vortex VR Lens on a violet studio backdrop",
    icon: SparklesIcon,
    price: 379,
    oldPrice: 540,
    discount: 30,
    rating: 4.5,
    reviews: 543,
  },
  {
    id: "pulse-buds",
    name: "Pulse Buds Pro",
    category: "Audio",
    description: "Wireless earbuds with lossless audio, ANC and IPX5 sweat-proofing.",
    tags: ["Lossless", "ANC", "IPX5"],
    href: "/product/pulse-buds",
    image: "/mock/products/pulse-buds.jpg",
    alt: "Pulse Buds Pro on a rose studio backdrop",
    icon: HeadphonesIcon,
    price: 149,
    oldPrice: 219,
    discount: 32,
    rating: 4.7,
    reviews: 3190,
  },
  {
    id: "nimbus-laptop",
    name: "Nimbus 16 Laptop",
    category: "Computing",
    description: "16-inch OLED laptop with a neural co-processor and 32GB memory.",
    tags: ["OLED", "32GB", "AI chip"],
    href: "/product/nimbus-laptop",
    image: "/mock/products/nimbus-laptop.jpg",
    alt: "Nimbus 16 Laptop on a blue studio backdrop",
    icon: LaptopIcon,
    price: 1899,
    oldPrice: 2299,
    discount: 17,
    rating: 4.9,
    reviews: 612,
    bestseller: true,
  },
  {
    id: "helix-console",
    name: "Helix Console",
    category: "Gaming",
    description: "Handheld-hybrid console with a 1440p OLED and dockable play.",
    tags: ["1440p", "OLED", "Hybrid"],
    href: "/product/helix-console",
    image: "/mock/products/helix-console.jpg",
    alt: "Helix Console on a purple studio backdrop",
    icon: GamepadIcon,
    price: 599,
    oldPrice: 749,
    discount: 20,
    rating: 4.8,
    reviews: 1458,
  },
  {
    id: "orbit-hub",
    name: "Orbit Home Hub",
    category: "Home",
    description: "Smart-home hub with on-device voice AI and Matter support.",
    tags: ["Matter", "Voice AI", "Zigbee"],
    href: "/product/orbit-hub",
    image: "/mock/products/orbit-hub.jpg",
    alt: "Orbit Home Hub on a warm studio backdrop",
    icon: HouseIcon,
    price: 129,
    oldPrice: 179,
    discount: 28,
    rating: 4.6,
    reviews: 928,
  },
  {
    id: "nova-soundbar",
    name: "Nova Soundbar 5.1",
    category: "Audio",
    description: "Cinematic 5.1 soundbar with a wireless sub and Dolby Atmos.",
    tags: ["Dolby Atmos", "Wireless sub", "HDMI eARC"],
    href: "/product/nova-soundbar",
    image: "/mock/product-showcase.jpg",
    alt: "Nova Soundbar 5.1",
    icon: HeadphonesIcon,
    price: 499,
    oldPrice: 699,
    discount: 29,
    rating: 4.6,
    reviews: 742,
  },
  {
    id: "echo-mini-speaker",
    name: "Echo Mini Speaker",
    category: "Audio",
    description: "Palm-sized smart speaker with 360° sound and on-device voice AI.",
    tags: ["360° sound", "Voice AI", "IPX6"],
    href: "/product/echo-mini-speaker",
    image: "/mock/product-showcase.jpg",
    alt: "Echo Mini Speaker",
    icon: HeadphonesIcon,
    price: 89,
    oldPrice: 129,
    discount: 31,
    rating: 4.4,
    reviews: 1533,
  },
  {
    id: "studio-monitor-buds",
    name: "Studio Monitor Buds",
    category: "Audio",
    description: "Reference-tuned earbuds with hi-res lossless audio and 32-hour battery.",
    tags: ["Hi-Res", "Lossless", "32h"],
    href: "/product/studio-monitor-buds",
    image: "/mock/product-showcase.jpg",
    alt: "Studio Monitor Buds",
    icon: HeadphonesIcon,
    price: 179,
    oldPrice: 229,
    discount: 22,
    rating: 4.7,
    reviews: 655,
    bestseller: true,
  },
  {
    id: "aura-band-lite",
    name: "Aura Band Lite",
    category: "Wearables",
    description: "Featherlight fitness band with a 21-day battery and sleep AI.",
    tags: ["21-day", "SpO2", "Sleep AI"],
    href: "/product/aura-band-lite",
    image: "/mock/product-showcase.jpg",
    alt: "Aura Band Lite",
    icon: WatchIcon,
    price: 59,
    oldPrice: 89,
    discount: 34,
    rating: 4.5,
    reviews: 2890,
  },
  {
    id: "halo-smart-ring",
    name: "Halo Smart Ring",
    category: "Wearables",
    description: "Titanium smart ring tracking recovery, HRV and sleep quality.",
    tags: ["Titanium", "HRV", "7-day"],
    href: "/product/halo-smart-ring",
    image: "/mock/product-showcase.jpg",
    alt: "Halo Smart Ring",
    icon: WatchIcon,
    price: 299,
    oldPrice: 349,
    discount: 14,
    rating: 4.3,
    reviews: 431,
  },
  {
    id: "lumen-ar-glasses",
    name: "Lumen AR Glasses",
    category: "Wearables",
    description: "Everyday AR glasses with a bright micro-OLED HUD and voice control.",
    tags: ["Micro-OLED", "6h", "Voice"],
    href: "/product/lumen-ar-glasses",
    image: "/mock/product-showcase.jpg",
    alt: "Lumen AR Glasses",
    icon: SparklesIcon,
    price: 549,
    oldPrice: 699,
    discount: 21,
    rating: 4.2,
    reviews: 288,
    bestseller: true,
  },
  {
    id: "nimbus-tab-11",
    name: "Nimbus Tab 11",
    category: "Computing",
    description: "11-inch OLED tablet with a neural chip and precision stylus support.",
    tags: ["OLED", "Neural chip", "Stylus"],
    href: "/product/nimbus-tab-11",
    image: "/mock/product-showcase.jpg",
    alt: "Nimbus Tab 11",
    icon: LaptopIcon,
    price: 649,
    oldPrice: 799,
    discount: 19,
    rating: 4.7,
    reviews: 934,
  },
  {
    id: "flux-keyboard",
    name: "Flux Mechanical Keyboard",
    category: "Computing",
    description: "Hot-swap mechanical keyboard with a gasket mount and per-key RGB.",
    tags: ["Hot-swap", "Gasket", "RGB"],
    href: "/product/flux-keyboard",
    image: "/mock/product-showcase.jpg",
    alt: "Flux Mechanical Keyboard",
    icon: LaptopIcon,
    price: 129,
    oldPrice: 169,
    discount: 24,
    rating: 4.8,
    reviews: 1122,
  },
  {
    id: "vista-27-monitor",
    name: "Vista 27 Monitor",
    category: "Computing",
    description: "27-inch 4K 144Hz monitor with HDR and 90W USB-C charging.",
    tags: ["4K", "144Hz", "USB-C"],
    href: "/product/vista-27-monitor",
    image: "/mock/product-showcase.jpg",
    alt: "Vista 27 Monitor",
    icon: LaptopIcon,
    price: 429,
    oldPrice: 549,
    discount: 22,
    rating: 4.6,
    reviews: 587,
  },
  {
    id: "helix-controller",
    name: "Helix Controller Pro",
    category: "Gaming",
    description: "Pro controller with hall-effect sticks, back paddles and low latency.",
    tags: ["Hall-effect", "Paddles", "Low latency"],
    href: "/product/helix-controller",
    image: "/mock/product-showcase.jpg",
    alt: "Helix Controller Pro",
    icon: GamepadIcon,
    price: 149,
    oldPrice: 199,
    discount: 25,
    rating: 4.7,
    reviews: 803,
  },
  {
    id: "raptor-headset",
    name: "Raptor Gaming Headset",
    category: "Gaming",
    description: "Wireless gaming headset with spatial audio and a 50-hour battery.",
    tags: ["Spatial", "50h", "Low latency"],
    href: "/product/raptor-headset",
    image: "/mock/product-showcase.jpg",
    alt: "Raptor Gaming Headset",
    icon: HeadphonesIcon,
    price: 119,
    oldPrice: 159,
    discount: 25,
    rating: 4.5,
    reviews: 1490,
  },
  {
    id: "pocket-arcade",
    name: "Pocket Arcade Handheld",
    category: "Gaming",
    description: "Retro-modern handheld with a 5-inch OLED and instant cloud play.",
    tags: ["OLED", "Cloud play", "8h"],
    href: "/product/pocket-arcade",
    image: "/mock/product-showcase.jpg",
    alt: "Pocket Arcade Handheld",
    icon: GamepadIcon,
    price: 279,
    oldPrice: 329,
    discount: 15,
    rating: 4.4,
    reviews: 612,
    bestseller: true,
  },
  {
    id: "aura-security-cam",
    name: "Aura Security Cam",
    category: "Home",
    description: "2K outdoor camera with on-device AI person detection and solar power.",
    tags: ["2K", "AI detect", "Solar"],
    href: "/product/aura-security-cam",
    image: "/mock/product-showcase.jpg",
    alt: "Aura Security Cam",
    icon: HouseIcon,
    price: 99,
    oldPrice: 149,
    discount: 34,
    rating: 4.5,
    reviews: 2044,
  },
  {
    id: "glow-bulb-kit",
    name: "Glow Smart Bulb Kit",
    category: "Home",
    description: "Four-pack of 16M-colour smart bulbs with Matter and custom scenes.",
    tags: ["Matter", "16M colours", "Scenes"],
    href: "/product/glow-bulb-kit",
    image: "/mock/product-showcase.jpg",
    alt: "Glow Smart Bulb Kit",
    icon: HouseIcon,
    price: 79,
    oldPrice: 109,
    discount: 28,
    rating: 4.3,
    reviews: 1360,
  },
  {
    id: "bolt-smart-lock",
    name: "Bolt Smart Lock",
    category: "Home",
    description: "Fingerprint smart lock with auto-unlock and a 12-month battery.",
    tags: ["Fingerprint", "Auto-unlock", "Matter"],
    href: "/product/bolt-smart-lock",
    image: "/mock/product-showcase.jpg",
    alt: "Bolt Smart Lock",
    icon: HouseIcon,
    price: 189,
    oldPrice: 239,
    discount: 21,
    rating: 4.6,
    reviews: 498,
  },
  {
    id: "skyline-drone-pro",
    name: "Skyline Drone Pro",
    category: "Aerial",
    description: "8K cinematic drone with a 45-minute flight time and tracking AI.",
    tags: ["8K", "45-min", "Tracking AI"],
    href: "/product/skyline-drone-pro",
    image: "/mock/product-showcase.jpg",
    alt: "Skyline Drone Pro",
    icon: SparklesIcon,
    price: 899,
    oldPrice: 1149,
    discount: 22,
    rating: 4.8,
    reviews: 356,
    bestseller: true,
  },
];

/** Curated subset shown in the homepage flash-deals carousel. */
export const flashDeals: Product[] = products.slice(0, 8);

const productById = new Map(products.map((p) => [p.id, p]));

/** Full catalogue detail for a product id (rating, specs, description…). */
export function getProduct(id: string): Product | undefined {
  return productById.get(id);
}
